pin foundry to v.1.3.5
with the latest version we get

    error: invalid value './hyperlane/chains/destination/state.json' for
    '--load-state <PATH>': failed to parse json file:
    "./hyperlane/chains/destination/state.json": missing field `index` at
    line 1 column 1260339