Ma/fix ci 2 (#26)
* pin foundry to v.1.3.5

with the latest version we get

    error: invalid value './hyperlane/chains/destination/state.json' for
    '--load-state <PATH>': failed to parse json file:
    "./hyperlane/chains/destination/state.json": missing field `index` at
    line 1 column 1260339

* remove left-over submodule in git index

* fix: installing deps once should suffice :D

* fix: tmux failures are hard to debug (#25)

* fix: tmux failures are hard to debug

- use process-compose instead

We can drop this once we move anvil to docker compose.

* fix: installing process-compose is slow

---------

Co-authored-by: Mathis Antony <sveitser@gmail.com>